openapi: 3.0.3
info:
  title: DiscogsAgent Proxy API
  version: 0.1.0
servers:
  - url: https://{host}
    variables:
      host:
        default: example.azurewebsites.net
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
security:
  - ApiKeyHeader: []
paths:
  /artists/{artist_id}:
    get:
      summary: Get an artist (proxied)
      operationId: getArtistProxy
      parameters:
        - name: artist_id
          in: path
          required: true
          schema:
            type: integer
          example: 108713
      responses:
        '200':
          description: OK
        '404':
          description: Not found
        '401':
          description: Unauthorized
  /releases/{release_id}:
    get:
      summary: Get a release (proxied)
      operationId: getReleaseProxy
      parameters:
        - name: release_id
          in: path
          required: true
          schema:
            type: integer
          example: 249504
      responses:
        '200': { description: OK }
        '404': { description: Not found }
        '401': { description: Unauthorized }
  /database/search:
    get:
      summary: Search database (proxied)
      operationId: searchDatabaseProxy
      parameters:
        - in: query
          name: q
          schema: { type: string }
          description: Free text query
        - in: query
          name: type
          schema: { type: string, enum: [release, master, artist, label] }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: per_page
          schema: { type: integer, minimum: 1, maximum: 100, default: 50 }
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }
